[package]
name = "udpqueue"
version = "0.2.6"
edition = "2021"

[dependencies]
jni = "0.21"

[lib]
crate_type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"
panic = "abort"
